//! Integration tests for embedded file attachments (`detach` /
//! pdfdetach-equivalent): listing, byte-exact extraction, checksum
//! verification, path-traversal sanitization, and cross-checks against
//! Poppler's `pdfdetach` when available.
//!
//! Fixtures are generated by `scripts/make_attachment_fixtures.py`:
//!   attach_nametree.pdf  - 1 file via /Names /EmbeddedFiles (+ MD5 checksum)
//!   attach_annot.pdf     - 1 file via a /FileAttachment annotation
//!   attach_traversal.pdf - 1 file named "../../evil.txt"
//!   attach_none.pdf      - no attachments

use std::path::PathBuf;
use std::process::Command;

use wellfriendpdf_engine::{sanitize_filename, ContentEngine};

const NAMETREE_PAYLOAD: &[u8] = b"Hello, embedded world!\nThis is a name-tree attachment.\n";
const NAMETREE_MD5_HEX: &str = "8AAF29AB3BEB5EF2EC29722EEC52A835";

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn engine(name: &str) -> ContentEngine {
    ContentEngine::open_bytes(std::fs::read(fixture(name)).unwrap()).unwrap()
}

fn poppler_pdfdetach() -> Option<PathBuf> {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    if let Some(root) = manifest.parent().and_then(|p| p.parent()) {
        let base = root.join("target").join("tools").join("poppler");
        if base.is_dir() {
            if let Some(found) = find_under(&base, "pdfdetach") {
                return Some(found);
            }
        }
    }
    let candidate = if cfg!(windows) {
        "pdfdetach.exe"
    } else {
        "pdfdetach"
    };
    Command::new(candidate)
        .arg("-v")
        .output()
        .ok()
        .map(|_| PathBuf::from(candidate))
}

fn find_under(dir: &std::path::Path, tool: &str) -> Option<PathBuf> {
    let exe = if cfg!(windows) {
        format!("{tool}.exe")
    } else {
        tool.to_string()
    };
    let mut subdirs = Vec::new();
    for entry in std::fs::read_dir(dir).ok()?.flatten() {
        let path = entry.path();
        if path.is_dir() {
            subdirs.push(path);
        } else if path.file_name().and_then(|n| n.to_str()) == Some(exe.as_str()) {
            return Some(path);
        }
    }
    for sub in subdirs {
        if let Some(found) = find_under(&sub, tool) {
            return Some(found);
        }
    }
    None
}

#[test]
fn lists_name_tree_attachment() {
    let e = engine("attach_nametree.pdf");
    let atts = e.list_attachments().unwrap();
    assert_eq!(atts.len(), 1, "expected exactly one attachment");
    let a = &atts[0];
    assert_eq!(a.name, "Hello.txt");
    assert_eq!(a.size, Some(NAMETREE_PAYLOAD.len()));
    assert_eq!(a.description.as_deref(), Some("test attachment"));
    assert_eq!(a.checksum_md5.as_deref(), Some(NAMETREE_MD5_HEX));
}

#[test]
fn extracts_name_tree_attachment_byte_exact() {
    let e = engine("attach_nametree.pdf");
    let atts = e.list_attachments().unwrap();
    let bytes = e.extract_attachment(&atts[0]).unwrap();
    assert_eq!(
        bytes, NAMETREE_PAYLOAD,
        "extracted bytes must equal the original payload exactly"
    );
}

#[test]
fn lists_and_extracts_annotation_attachment() {
    let e = engine("attach_annot.pdf");
    let atts = e.list_attachments().unwrap();
    assert_eq!(atts.len(), 1, "annotation attachment must be found");
    assert_eq!(atts[0].name, "annot-data.bin");

    let bytes = e.extract_attachment(&atts[0]).unwrap();
    // The generator's annot payload is range(0..256) twice = 512 bytes.
    let expected: Vec<u8> = (0u16..256).chain(0u16..256).map(|b| b as u8).collect();
    assert_eq!(bytes.len(), 512);
    assert_eq!(
        bytes, expected,
        "annotation payload must extract byte-exact"
    );
}

#[test]
fn no_attachments_returns_empty_not_error() {
    let e = engine("attach_none.pdf");
    let atts = e.list_attachments().unwrap();
    assert!(atts.is_empty(), "a PDF with no attachments must list empty");
}

#[test]
fn path_traversal_name_is_sanitized_on_extraction() {
    let e = engine("attach_traversal.pdf");
    let atts = e.list_attachments().unwrap();
    assert_eq!(atts.len(), 1);
    // The raw name is the malicious "../../evil.txt".
    assert_eq!(atts[0].name, "../../evil.txt");

    // Sanitization must collapse it to a single safe component.
    let safe = sanitize_filename(&atts[0].name);
    assert_eq!(
        safe, "evil.txt",
        "traversal must be stripped to the base name"
    );
    assert!(!safe.contains('/') && !safe.contains('\\') && !safe.contains(".."));

    // And actually writing it into a temp dir must stay inside that dir.
    let dir = std::env::temp_dir().join("wellfriendpdf_attach_traversal_test");
    let _ = std::fs::create_dir_all(&dir);
    let target = dir.join(&safe);
    let bytes = e.extract_attachment(&atts[0]).unwrap();
    std::fs::write(&target, &bytes).unwrap();
    // The written file must be a direct child of `dir` (no escape).
    assert_eq!(target.parent().unwrap(), dir);
    assert!(target.exists());
    let _ = std::fs::remove_file(&target);
    let _ = std::fs::remove_dir(&dir);
}

#[test]
fn dedupes_attachments_by_stream_object() {
    // The name-tree fixture references its embedded-file stream once; ensure we
    // never double-count. (Dedup logic is also covered structurally — a single
    // stream id maps to a single Attachment.)
    let e = engine("attach_nametree.pdf");
    let atts = e.list_attachments().unwrap();
    let mut ids: Vec<(u32, u16)> = atts
        .iter()
        .map(|a| (a.stream_object, a.stream_generation))
        .collect();
    let before = ids.len();
    ids.sort_unstable();
    ids.dedup();
    assert_eq!(before, ids.len(), "no duplicate stream ids in the listing");
}

#[test]
fn cross_check_pdfdetach_list_and_bytes() {
    let Some(tool) = poppler_pdfdetach() else {
        eprintln!("NOTE: pdfdetach not found; skipping cross-check");
        return;
    };

    for (fix, expected_count) in [
        ("attach_nametree.pdf", 1usize),
        ("attach_annot.pdf", 1),
        ("attach_traversal.pdf", 1),
        ("attach_none.pdf", 0),
    ] {
        let path = fixture(fix);
        // -list: first line is "N embedded files".
        let out = Command::new(&tool)
            .arg("-list")
            .arg(&path)
            .output()
            .unwrap();
        let listing = String::from_utf8_lossy(&out.stdout);
        let poppler_count: usize = listing
            .lines()
            .next()
            .and_then(|l| l.split_whitespace().next())
            .and_then(|n| n.parse().ok())
            .unwrap_or(0);
        assert_eq!(
            poppler_count, expected_count,
            "{fix}: pdfdetach count sanity"
        );

        let e = engine(fix);
        let atts = e.list_attachments().unwrap();
        assert_eq!(
            atts.len(),
            poppler_count,
            "{fix}: Wellfriend attachment count disagrees with pdfdetach"
        );
    }

    // Byte-level agreement: pdfdetach -saveall vs Wellfriend extraction on nametree.
    let dir = std::env::temp_dir().join("wellfriendpdfdetach_xcheck");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let status = Command::new(&tool)
        .arg("-saveall")
        .arg("-o")
        .arg(&dir)
        .arg(fixture("attach_nametree.pdf"))
        .status()
        .unwrap();
    assert!(status.success());
    let poppler_bytes = std::fs::read(dir.join("Hello.txt")).unwrap();

    let e = engine("attach_nametree.pdf");
    let atts = e.list_attachments().unwrap();
    let wellfriendpdf_bytes = e.extract_attachment(&atts[0]).unwrap();
    assert_eq!(
        wellfriendpdf_bytes, poppler_bytes,
        "Wellfriend-extracted bytes must equal pdfdetach-extracted bytes"
    );
    let _ = std::fs::remove_dir_all(&dir);
}
